platform :ios, '13.2'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Currency Conversion Scanner' do
  pod 'LTMorphingLabel'
  pod 'RAMAnimatedTabBarController'
end
